### ISSUE TITLE
Scam Account Submission

### ISSUE THREAD

**Issue by Xprogrammer777** [ThioJoe/YT-Spam-Lists#194]
### Duplicate Submissions

- [X] Yes, I checked that the account name **is not currently in the list**
- [X] I read <a href=https://github.com/ThioJoe/YT-Spam-Domains-List/wiki>the wiki</a> explaining each different categories and examples before submitting

### (Required) Spam Comment Direct Link

https://www.youtube.com/channel/UCqEqyssXROPfn8GmkIsNI4g
https://www.youtube.com/channel/UCEZ9stq9GSz3svX4tvYwqWw
https://www.youtube.com/channel/UCIssHT9x7-SE5A0RBluGu4g
https://www.youtube.com/channel/UC7hhCp03MHqVKbZGDM0JjSg
https://www.youtube.com/channel/UC6vw-_k1LRKu6C9K0cLFHBw/videos

### (Required) List of the scam account names

contact soubhack on instagram he's trustworthy
soubhack on ig is The Best💯❤️
message soubhack on instagram he can help you…

**Comment by Xprogrammer777** [comment]
What still active? Wow

**Comment by Firecul** [comment]
In the future, it'd be best if you could also link a comment showing them advertising, rather than just linking to their channels, please. I have added that one to the lists anyway.
