### ISSUE TITLE
Spam Domain Submission

### ISSUE THREAD

**Issue by koviubi56** [ThioJoe/YT-Spam-Lists#208]
### Duplicate Domains

- [X] Yes, I checked that the domain **is not currently in the list**
- [X] I read <a href=https://github.com/ThioJoe/YT-Spam-Domains-List/wiki>the wiki</a> explaining each different categories and examples before submitting

### (Required) Spam Comment Direct Link

https://www.youtube.com/watch?v=GZC8OVEA9Z8&lc=UgyBTDZjmPbN3AbYLm14AaABAg

### (Optional) Screenshot of comments using the domain

![image](https://user-images.githubusercontent.com/58398849/195998065-7cf48f9a-b7e8-44f5-92a4-ded04a47a491.png)

### (Required) List of the spam domains

alove.cam

**Comment by ThioJoe** [comment]
Added
