### ISSUE TITLE
Spam Video ID Submission: Missed spam comments, using Auto-Smart Mode

### ISSUE THREAD

**Issue by Engstory** [ThioJoe/YT-Spam-Lists#237]
### Duplicate Links

- [X] Yes, I checked that the ID **is not currently in the list**
- [X] I read <a href=https://github.com/ThioJoe/YT-Spam-Domains-List/wiki>the wiki</a> explaining each different categories and examples before submitting

### (Required) Spam Comment Direct Link

https://www.youtube.com/watch?v=YL_Efp4H6z0&lc=Ugw6mtHgMxT3I5mibsN4AaABAg.9i3G_GpRyGa9i4G76Hx8cA
https://www.youtube.com/watch?v=YL_Efp4H6z0&lc=UgwTbpBvYOQQ-S-DzQN4AaABAg.9i3Yc10aqQk9i4G5S7m-qF
https://www.youtube.com/watch?v=YL_Efp4H6z0&lc=UgxJpTCWzqjIDtS2bAt4AaABAg.9i3AQUZRm7e9i4G3ZHO2XB
https://www.youtube.com/watch?v=YL_Efp4H6z0&lc=Ugx5_SxYt4CBK5MA6dp4AaABAg.9i3OxJiM-749i4G1yZs_CY

### (Optional) Screenshot of comments using the link

![image](https://user-images.githubusercontent.com/99150304/204231236-972f9a2f-8dda-468e-98f0-7818f680bce1.png)
![image](https://user-images.githubusercontent.com/99150304/204231268-2f3f5e21-f452-4c21-8618-7a767ec2949b.png)
![image](https://user-images.githubusercontent.com/99150304/204231337-4a7f0e7d-7513-4ebc-a6f6-6df172e20359.png)
![image](https://user-images.githubusercontent.com/99150304/204231376-51149dd0-d570-4964-b00b-849b1accbc5e.png)

### (Required) List of the spam video IDs / Links

https://youtu.be/YL_Efp4H6z0

**Comment by Engstory** [comment]
Huh, this issue still haven't been resolved, is the problem being the language is not English?

**Comment by Firecul** [comment]
> Huh, this issue still haven't been resolved, is the problem being the language is not English?

Probably tbh (See ThioJoe's comment to a similar* post below)

> It really wouldn't make a difference because very little of the filter even looks for whole words. I'm just going to close this because tbh I don't really intend to implement any kind of translation functionality.
If there is a pattern of a certain type of spammer in another language I'll take a look and see what I can do. But I'd need actual specific examples

https://github.com/ThioJoe/YT-Spammer-Purge/issues/496#issuecomment-1029364509

**Comment by Engstory** [comment]
Got it, thanks for the clarification!
