### ISSUE TITLE
Spam Domain Submission

### ISSUE THREAD

**Issue by cochcoder** [ThioJoe/YT-Spam-Lists#350]
### Duplicate Domains

- [X] Yes, I checked that the domain **is not currently in the list**
- [X] I read <a href=https://github.com/ThioJoe/YT-Spam-Domains-List/wiki>the wiki</a> explaining each different categories and examples before submitting

### (Required) Spam Comment Direct Link

https://youtube.com/shorts/s2xB2fHEn0k?feature=share

### (Optional) Screenshot of comments using the domain

![8A304879-11E1-4D5B-BB7B-80007A2B2B59](https://user-images.githubusercontent.com/103969142/226150441-fe1fbdf9-ead0-405e-9724-28e5fe9f5d99.jpeg)

Note - I tried to get the original video (which is still up as a ad) in here. However, as the video is unlisted and I can’t seem to get the ad up again I’m using this react video instead to show proof of the scam domain. 

### (Required) List of the spam domains

beast-prm.com

**Comment by Firecul** [comment]
We can't really police what people put up on their own channels imo. If they were posting this elsewhere sure but on to their own video is a different matter.
I can still add if ThioJoe feels differently on this though.

**Comment by cochcoder** [comment]
I realize that adding this domain will probably do nothing as you said.
