### ISSUE TITLE
Scam Account Submission

### ISSUE THREAD

**Issue by 2NumForIce** [ThioJoe/YT-Spam-Lists#411]
### Duplicate Submissions

- [x] Yes, I checked that the account name **is not currently in the list**
- [X] I read <a href=https://github.com/ThioJoe/YT-Spam-Domains-List/wiki>the wiki</a> explaining each different categories and examples before submitting

### (Required) Spam Comment Direct Link

https://www.youtube.com/watch?v=mkKteoXE-X0&lc=Ugwy0bVM3lIvW13F5eF4AaABAg.9cACCYYPF1Q9cACf5p7pOT
https://www.youtube.com/watch?v=mkKteoXE-X0&lc=UgzknzeolDUsVdN_SDJ4AaABAg.9c0asfvbhyO9c0atYACBDW
https://www.youtube.com/watch?v=mkKteoXE-X0&lc=Ugy6N6xCy_9OEv1CwF14AaABAg.9c3SMmzkwmo9c3TzGIVBJX
https://www.youtube.com/watch?v=mkKteoXE-X0&lc=Ugzx6BSoxXcxj4nDHPl4AaABAg.9cMi74dXkeh9cMxbEm2gfz
https://www.youtube.com/watch?v=mkKteoXE-X0&lc=Ugy2DaPYzXVrbVBRFG14AaABAg.9c-GKrlNJav9c-GiSLMio4
https://www.youtube.com/watch?v=mkKteoXE-X0&lc=UgyhqDstI5xsUL_Mb2F4AaABAg.9c0vGGGBom89c0vUzU4hxh
https://www.youtube.com/watch?v=mkKteoXE-X0&lc=UgxqQvUUbMuTuFOAbTB4AaABAg.9c3_x1B4HhT9c3aKTVwEJg
https://www.youtube.com/watch?v=mkKteoXE-X0&lc=UgwILt6WeqN4yJBCc1l4AaABAg.9cOPEBCihb-9cOQo15g5_Q
https://www.youtube.com/watch?v=mkKteoXE-X0&lc=Ugyn6H7E7K5nREByrbR4AaABAg.9cGwoVkjyV69cGynsgXYHD
https://www.youtube.com/watch?v=mkKteoXE-X0&lc=UgxI9n19yy2qmD0q0lR4AaABAg.9c8gCoWL4Ii9c8jZUQgTdm
https://www.youtube.com/watch?v=mkKteoXE-X0&lc=Ugyl2IWPnfYyMK6yMBB4AaABAg

### (Optional) Screenshot of comments referencing the scam account

I have only included 3 screenshots since there are 11 accounts and I'm not going to do them all.
<img width="555" alt="Screenshot 2023-06-17 at 10 14 51 AM" src="https://github.com/ThioJoe/YT-Spam-Lists/assets/127453854/a37b2ef0-d415-4bbe-a093-10c6d7610ad9">
<img width="410" alt="Screenshot 2023-06-17 at 10 23 33 AM" src="https://github.com/ThioJoe/YT-Spam-Lists/assets/127453854/bea3ed55-aa9b-464e-855b-e38cb01b1245">
<img width="955" alt="Screenshot 2023-06-17 at 10 29 59 AM" src="https://github.com/ThioJoe/YT-Spam-Lists/assets/127453854/bf47b99f-0e58-4008-8509-ddefd4341b6b">
c63a-8c7a-4fcf-86d4-3b08fedf4c90">

### (Required) List of the scam account names

benazelart6
its_beatemups
juliotoolz_
mrbeastofficial01
mrbeast_12
rollytool
mrbeast010
mrbenz0
official_atq
pewdiepie.033
kizlarse

**Comment by Firecul** [comment]
@ThioJoe would it better to put their @ names in the list or the accounts mentioned on their actual page?

**Comment by Firecul** [comment]
Looks like I'm not getting an answer on this one, I'll go with the names you suggested
