### ISSUE TITLE
Spam Domain Submission

### ISSUE THREAD

**Issue by 2NumForIce** [ThioJoe/YT-Spam-Lists#412]
### Duplicate Domains

- [X] Yes, I checked that the domain **is not currently in the list**
- [X] I read <a href=https://github.com/ThioJoe/YT-Spam-Domains-List/wiki>the wiki</a> explaining each different categories and examples before submitting

### (Required) Spam Comment Direct Link

https://www.youtube.com/watch?v=mkKteoXE-X0&lc=UgzKgrsn8oc6BRCTZM14AaABAg
https://www.youtube.com/watch?v=mkKteoXE-X0&lc=Ugy9kynuLDg2pXf4Ftl4AaABAg
https://www.youtube.com/watch?v=mkKteoXE-X0&lc=UgzWolW_bJvh4-Hzgdx4AaABAg
https://www.youtube.com/watch?v=mkKteoXE-X0&lc=UgxCZS5SpzHkXpYIOf94AaABAg

### (Optional) Screenshot of comments using the domain

<img width="484" alt="Screenshot 2023-06-17 at 10 49 31 AM" src="https://github.com/ThioJoe/YT-Spam-Lists/assets/127453854/969a1f83-37fc-417e-be4c-dd9266426a83">
<img width="562" alt="Screenshot 2023-06-17 at 10 50 05 AM" src="https://github.com/ThioJoe/YT-Spam-Lists/assets/127453854/0cc93869-7493-4219-8326-cdf5bf0c5304">
I have also reported the website using ThioJoe's guide.
<img width="1108" alt="Screenshot 2023-06-17 at 10 50 19 AM" src="https://github.com/ThioJoe/YT-Spam-Lists/assets/127453854/d9144cf8-98d6-4660-9a75-85d509fc5b56">

### (Required) List of the spam domains

robuxifythis.cfd

**Comment by Firecul** [comment]
While it is a spam domain, since they don't mention it in a comment adding it to the lists would not help their comments to be detected and flagged as spam.

**Comment by Firecul** [comment]
Since we don't seem to be getting an answer from @ThioJoe 
While they are a bot we don't currently have a category to add it to sorry.
