### ISSUE TITLE
Spam Account Submission

### ISSUE THREAD

**Issue by Engstory** [ThioJoe/YT-Spam-Lists#441]
### Duplicate Submissions

- [X] Yes, I checked that the account name **is not currently in the list**
- [X] I read <a href=https://github.com/ThioJoe/YT-Spam-Domains-List/wiki>the wiki</a> explaining each different categories and examples before submitting

### (Required) Spam Comment Direct Link

https://www.youtube.com/watch?v=MPLy4C4TXJE&lc=UgwszhQbS7bHyEs4B9Z4AaABAg.9tQ066VYUIq9tQ0Fgpn0Vq
https://www.youtube.com/watch?v=MPLy4C4TXJE&lc=UgyjUS_Qz6pQb_Qs-7N4AaABAg.9tQ0C3Hr1Rn9tQ0U7fxksS

### (Optional) Screenshot of comments referencing the scam account

![image](https://github.com/ThioJoe/YT-Spam-Lists/assets/99150304/a509f837-34a3-4b26-a022-f897f622ffb7)
![image](https://github.com/ThioJoe/YT-Spam-Lists/assets/99150304/7f603d02-c659-4bdc-b80e-514b9bcde210)

### (Required) List of the scam account names

[RomanisRandom](https://www.youtube.com/channel/UCk-21cIVYDbnJMNb6N5vcMg)

**Comment by Firecul** [comment]
While they are a bot we don't currently have a category to add it to sorry.
