### ISSUE TITLE
Scam Thread Submission

### ISSUE THREAD

**Issue by Engstory** [ThioJoe/YT-Spam-Lists#448]
### Duplicate Submissions

- [X] Yes, I checked that the name **is not currently in the list**
- [X] I read <a href=https://github.com/ThioJoe/YT-Spam-Domains-List/wiki>the wiki</a> explaining each different categories and examples before submitting

### (Required) Spam Comment Direct Link

https://www.youtube.com/watch?v=L25p9l6P9V4&lc=UgzgVSwLHEFDqcYeyuJ4AaABAg
https://www.youtube.com/channel/UCZef4WyFYbaNg47Dm4PCCuw
https://www.youtube.com/channel/UCS1fmvPvk2eA7MBPdfSMjGA

### (Optional) Screenshot of comments referencing the scammer names

![image](https://github.com/ThioJoe/YT-Spam-Lists/assets/99150304/dc85cc3e-2604-465c-9bc0-75f407fc51a6)

### (Required) List of the scammer names

[@Tey-ge9sc](https://www.youtube.com/channel/UCiBZhEXwGrBfQbwa_4xhJFA)
[@Rayyyyyy1113](https://www.youtube.com/channel/UCs8JDqkg72JcgzPxxmn_Neg)
[Sasha2cox](https://www.youtube.com/channel/UCZef4WyFYbaNg47Dm4PCCuw)
[Sadiwskiaaron](https://www.youtube.com/channel/UCS1fmvPvk2eA7MBPdfSMjGA)

**Comment by Firecul** [comment]
I've added `LUCY ROSE CARTER` to the lists as that's the appropriate part for this thread
