### ISSUE TITLE
Scam Thread Submission

### ISSUE THREAD

**Issue by Kurdakov** [ThioJoe/YT-Spam-Lists#59]
### Duplicate Submissions

- [X] Yes, I checked that the name **is not currently in the list**
- [X] I read <a href=https://github.com/ThioJoe/YT-Spam-Domains-List/wiki>the wiki</a> explaining each different categories and examples before submitting

### (Required) Spam Comment Direct Link

https://www.youtube.com/channel/UCBJycsmduvYEL83R_U4JriQ/community?lc=UgxC-s6IGJDD1WsgMCh4AaABAg&lb=UgznRp21lpKOOn8WCIp4AaABCQ

https://www.youtube.com/channel/UCBJycsmduvYEL83R_U4JriQ/community?lc=Ugzp8NwPp0BycSW_ncl4AaABAg&lb=Ugy2f59nirXqIwhf_Hh4AaABCQ

### (Required) List of the scammer names

ms. elizabeth armstrong palmer
elizabeth a. palmer
mrs elizabeth
ms pamela
mrs pamela

**Comment by Firecul** [comment]
`Ms Pamela`
Was also used in that thread

**Comment by Kurdakov** [comment]
ok and also
mrs pamela

**Comment by Kurdakov** [comment]
> `Ms Pamela` Was also used in that thread

edited submission
