### ISSUE TITLE
five new scam domains!

### ISSUE THREAD

**Issue by prettybadatcoding** [ThioJoe/YT-Spam-Lists#64]
### Duplicate Domains

- [X] Yes, I checked that the domain **is not currently in the list**
- [X] I read <a href=https://github.com/ThioJoe/YT-Spam-Domains-List/wiki>the wiki</a> explaining each different categories and examples before submitting

### (Required) Spam Comment Direct Link

https://www.youtube.com/watch?v=X-NboeQ-yjw&lc=UgxSELOq1aXLBwc7hvJ4AaABAg
https://www.youtube.com/watch?v=X-NboeQ-yjw&lc=UgwKadT7vzQQj50X3Jh4AaABAg
https://www.youtube.com/watch?v=X-NboeQ-yjw&lc=UgyOJQXyO4FAVfhJaeJ4AaABAg
https://www.youtube.com/watch?v=X-NboeQ-yjw&lc=UgwnI_KKqDpSacjlptJ4AaABAg
https://www.youtube.com/watch?v=X-NboeQ-yjw&lc=UgybX8kG0YsjppcdaHZ4AaABAg

### (Optional) Screenshot of comments using the domain

<img width="425" alt="scam" src="https://user-images.githubusercontent.com/97399364/148702777-909cd608-5ee5-49db-a0c9-04ddf6a570aa.png">
<img width="395" alt="scam0" src="https://user-images.githubusercontent.com/97399364/148702778-533d06af-6af0-40c1-9b2e-a904d0bb3cc0.png">
<img width="419" alt="scam2" src="https://user-images.githubusercontent.com/97399364/148702786-133690ed-eea4-470d-a2da-4bbf2d55d870.png">
<img width="483" alt="scam3" src="https://user-images.githubusercontent.com/97399364/148702791-feaad33e-3395-4065-9631-e99f14c2bbee.png">
<img width="464" alt="scam4" src="https://user-images.githubusercontent.com/97399364/148702796-3508624d-93d1-4b4f-85c7-f6fc12bf485f.png">

### (Required) List of the spam domains

wedn.best
b.derk.bar
owap.bar
r.hhhh.uno
ozap.bar

**Comment by ThioJoe** [comment]
Added with 8f1f33699d15ef495869e532c69bd318023fa23b
