### ISSUE TITLE
Spam Domain Submission

### ISSUE THREAD

**Issue by MrArgon39** [ThioJoe/YT-Spam-Lists#65]
### Duplicate Domains

- [X] Yes, I checked that the domain **is not currently in the list**
- [X] I read <a href=https://github.com/ThioJoe/YT-Spam-Domains-List/wiki>the wiki</a> explaining each different categories and examples before submitting

### (Required) Spam Comment Direct Link

https://www.youtube.com/watch?v=cIANKXVKKuo&lc=Ugx65qrgrWq6KBmgYkB4AaABAg.9X-K1vMRFBl9X-LmiNCtQl

### (Required) List of the spam domains

asianteen.space

**Comment by ThioJoe** [comment]
Added with 8f1f33699d15ef495869e532c69bd318023fa23b
