### ISSUE TITLE
Scam Account Submission

### ISSUE THREAD

**Issue by TechStudent11** [ThioJoe/YT-Spam-Lists#68]
### Duplicate Submissions

- [X] Yes, I checked that the account name **is not currently in the list**
- [X] I read <a href=https://github.com/ThioJoe/YT-Spam-Domains-List/wiki>the wiki</a> explaining each different categories and examples before submitting

### (Required) Spam Comment Direct Link

https://www.youtube.com/watch?v=Dh909TbYn7Y&lc=Ugx33YSOTLWjI7CFWpp4AaABAg.9X0qrq2xB3P9X0uCK-UUPU
https://www.youtube.com/watch?v=Dh909TbYn7Y&lc=Ugx33YSOTLWjI7CFWpp4AaABAg.9X0qrq2xB3P9X14Jyrxigw

### (Optional) Screenshot of comments referencing the scam account

![image](https://user-images.githubusercontent.com/76978184/148814144-90b0c147-deb1-4d9b-b046-d05c833f59c0.png)
![image](https://user-images.githubusercontent.com/76978184/148814184-4b28dbe2-4133-453f-93d0-8a5d66d6b6e1.png)

### (Required) List of the scam account names

Yurika💋
GABRIELLA

**Comment by Kurdakov** [comment]
currently youtube spam accounts are not submitted (due to the fact those accounts frequently change). But your submission contains missing spam domain localdate.moster (another one is already is in spam domains) which was resubmitted here  https://github.com/ThioJoe/YT-Spammer-Purge/issues/371

**Comment by TechStudent11** [comment]
> currently youtube spam accounts are not submitted (due to the fact those accounts frequently change). But your submission contains missing spam domain localdate.moster (another one is already is in spam domains) which thopugh, was again resubmitted here [ThioJoe/YT-Spammer-Purge#371](https://github.com/ThioJoe/YT-Spammer-Purge/issues/371)

What???

**Comment by Kurdakov** [comment]
>What???

see on front page
"Spam Accounts: External social media accounts (instagram, telegram, etc) that are mentioned in scam comments as the point of contact for that particular scam. Usually these are scams advertising fake hacking services, free vbucks/robux, etc."

are Yurika💋 and GABRIELLA are external instagram, telegramm accounts?

**Comment by TechStudent11** [comment]
> > What???
> 
> see on front page "Spam Accounts: External social media accounts (instagram, telegram, etc) that are mentioned in scam comments as the point of contact for that particular scam. Usually these are scams advertising fake hacking services, free vbucks/robux, etc."
> 
> are Yurika💋 and GABRIELLA are external instagram, telegram accounts?

no?

**Comment by Kurdakov** [comment]
>no?

in another comment in another submission I was mistaken on instagram issue,
but here no references to instagram or telegram. Just a spam link and youtube account

**Comment by TechStudent11** [comment]
> > no?
> 
> in another comment in another submission I was mistaken on instagram issue, but here no references to instagram or telegram. Just a spam link and youtube account

ohhhhhhhhhh k.

**Comment by KendallDoesCoding** [comment]
Are these accounts or sites, they seem to be websites, in that case you need to open a "Scam Domain Submission" issue and not a "Spam Account Submission" form @TechStudent11

**Comment by KendallDoesCoding** [comment]
> Are these accounts or sites, they seem to be websites, in that case you need to open a "Scam Domain Submission" issue and not a "Spam Account Submission" form @TechStudent11

If it is a domain and not a account, I think it would be better if you close this issue and open another issue reporting this but as a Scam Domain instead of account, because even the label here now is scam-account.

**Comment by TechStudent11** [comment]
@KendallDoesCoding yeah I'll close this.
