### ISSUE TITLE
Scam Account Submission

### ISSUE THREAD

**Issue by PierceWHoward** [ThioJoe/YT-Spam-Lists#69]
### Duplicate Submissions

- [X] Yes, I checked that the account name **is not currently in the list**
- [X] I read <a href=https://github.com/ThioJoe/YT-Spam-Domains-List/wiki>the wiki</a> explaining each different categories and examples before submitting

### (Required) Spam Comment Direct Link

https://www.youtube.com/watch?v=JoU-5Mabsuc&lc=Ugx3v7_DL_prmNoHLg14AaABAg
https://www.youtube.com/watch?v=JoU-5Mabsuc&lc=UgzrW3HYSND3x9sDdOF4AaABAg
https://www.youtube.com/watch?v=JoU-5Mabsuc&lc=Ugy1MUJqEuZhBL0ymCB4AaABAg
https://www.youtube.com/watch?v=JoU-5Mabsuc&lc=UgxuqBhdYlHsMaNoja94AaABAg
https://www.youtube.com/watch?v=JoU-5Mabsuc&lc=UgyiaYzgduxwldh25o14AaABAg
https://www.youtube.com/watch?v=JoU-5Mabsuc&lc=UgzQxI8gwEoM-BUSOvp4AaABAg
https://www.youtube.com/watch?v=JoU-5Mabsuc&lc=UgyTzCfDa43JKf-bmJF4AaABAg
https://www.youtube.com/watch?v=JoU-5Mabsuc&lc=UgzgHku7LoXLz9f71-R4AaABAg
https://www.youtube.com/watch?v=JoU-5Mabsuc&lc=UgwPgPOIU9RiqUlR4cZ4AaABAg
https://www.youtube.com/watch?v=JoU-5Mabsuc&lc=UgzZEcybWi272v1O18p4AaABAg
https://www.youtube.com/watch?v=JoU-5Mabsuc&lc=UgwpX_LEKozxSA0LPsZ4AaABAg
https://www.youtube.com/watch?v=JoU-5Mabsuc&lc=Ugy658zy1LBD_e3KqN94AaABAg
https://www.youtube.com/watch?v=JoU-5Mabsuc&lc=Ugyv1UDg3Uv2JveLGJN4AaABAg
https://www.youtube.com/watch?v=JoU-5Mabsuc&lc=UgxmjpQ0YFAUdYgBiVd4AaABAg
https://www.youtube.com/watch?v=JoU-5Mabsuc&lc=Ugz5ASQG92P6KQQlbsF4AaABAg
https://www.youtube.com/watch?v=JoU-5Mabsuc&lc=UgwrIEt-PW6V2K7ZIEx4AaABAg
https://www.youtube.com/watch?v=JoU-5Mabsuc&lc=Ugyz_kqTmkJ7SvOMP3h4AaABAg
https://www.youtube.com/watch?v=JoU-5Mabsuc&lc=UgxOwKTcmbyo8oqvlw14AaABAg
https://www.youtube.com/watch?v=JoU-5Mabsuc&lc=UgzDjxXtQqBzliETDgN4AaABAg
https://www.youtube.com/watch?v=JoU-5Mabsuc&lc=UgxedLzLEDcZc0kL5rZ4AaABAg
https://www.youtube.com/watch?v=JoU-5Mabsuc&lc=UgwLfiOyvSXfTqn0Oet4AaABAg
https://www.youtube.com/watch?v=JoU-5Mabsuc&lc=UgwFNl95OLALCTh-azh4AaABAg
https://www.youtube.com/watch?v=JoU-5Mabsuc&lc=UgwFNl95OLALCTh-azh4AaABAg
https://www.youtube.com/watch?v=JoU-5Mabsuc&lc=UgwK3hhqGuOwJTvNdON4AaABAg
https://www.youtube.com/watch?v=JoU-5Mabsuc&lc=UgzLP1GnMMVN9S3goiN4AaABAg
https://www.youtube.com/watch?v=JoU-5Mabsuc&lc=UgyhCcfaOU_oMfips0F4AaABAg

### (Optional) Screenshot of comments referencing the scam account

<img width="641" alt="Screen Shot 2022-01-10 at 12 07 44 PM" src="https://user-images.githubusercontent.com/20427582/148832115-b2266358-20de-461e-89f1-e95bd71bea3d.png">
<img width="649" alt="Screen Shot 2022-01-10 at 12 09 22 PM" src="https://user-images.githubusercontent.com/20427582/148832312-029c298f-fcf9-421c-8da5-e2003d18356c.png">
<img width="629" alt="Screen Shot 2022-01-10 at 12 11 30 PM" src="https://user-images.githubusercontent.com/20427582/148832556-b84b1964-425f-4625-ab4a-7af2412713fe.png">
<img width="642" alt="Screen Shot 2022-01-10 at 12 12 32 PM" src="https://user-images.githubusercontent.com/20427582/148832664-0da7d4c9-68ac-4f6d-abac-67f9ffd1a44d.png">
<img width="649" alt="Screen Shot 2022-01-10 at 12 14 23 PM" src="https://user-images.githubusercontent.com/20427582/148832911-bfe8b179-e27f-479a-893e-0936922e2e06.png">
<img width="645" alt="Screen Shot 2022-01-10 at 12 15 26 PM" src="https://user-images.githubusercontent.com/20427582/148833006-b31ebf84-55b8-4902-a166-7dc8a6696618.png">
<img width="645" alt="Screen Shot 2022-01-10 at 12 16 13 PM" src="https://user-images.githubusercontent.com/20427582/148833101-4a8e85ea-6bb3-47b4-841a-b8819c258b18.png">
<img width="626" alt="Screen Shot 2022-01-10 at 12 16 47 PM" src="https://user-images.githubusercontent.com/20427582/148833184-efeb4a4f-b7b8-4617-b9d6-d19a988aaea4.png">
<img width="479" alt="Screen Shot 2022-01-10 at 12 18 11 PM" src="https://user-images.githubusercontent.com/20427582/148833331-f9e3c6a7-b550-489c-bf1b-b90273fecb7f.png">
<img width="484" alt="Screen Shot 2022-01-10 at 12 18 43 PM" src="https://user-images.githubusercontent.com/20427582/148833394-99374d66-9c39-4954-83d0-f4c5f16de84a.png">
<img width="646" alt="Screen Shot 2022-01-10 at 12 19 45 PM" src="https://user-images.githubusercontent.com/20427582/148833474-8838c343-d131-4e10-b951-e57b96654b7d.png">
<img width="646" alt="Screen Shot 2022-01-10 at 12 20 35 PM" src="https://user-images.githubusercontent.com/20427582/148833590-1704929b-0d1d-4e91-9722-d1e72e141f91.png">
<img width="643" alt="Screen Shot 2022-01-10 at 12 21 26 PM" src="https://user-images.githubusercontent.com/20427582/148833673-1e124e7c-ee98-4443-a4d7-8d1cbe8a5c60.png">
<img width="635" alt="Screen Shot 2022-01-10 at 12 21 59 PM" src="https://user-images.githubusercontent.com/20427582/148833737-b5e2a61a-d6de-4b0a-becc-816e70e51907.png">
<img width="646" alt="Screen Shot 2022-01-10 at 12 23 03 PM" src="https://user-images.githubusercontent.com/20427582/148833869-972b6c23-8990-496a-b449-178a44695193.png">
<img width="644" alt="Screen Shot 2022-01-10 at 12 23 47 PM" src="https://user-images.githubusercontent.com/20427582/148834031-bcfe3b36-e2eb-47f3-8548-d50f5deebe95.png">
<img width="657" alt="Screen Shot 2022-01-10 at 12 24 13 PM" src="https://user-images.githubusercontent.com/20427582/148834113-60fc281e-01ea-4c5b-ac22-065cfbac8948.png">
<img width="646" alt="Screen Shot 2022-01-10 at 12 24 54 PM" src="https://user-images.githubusercontent.com/20427582/148834200-a976077d-e57b-4408-8930-a309bebc5fe3.png">
<img width="638" alt="Screen Shot 2022-01-10 at 12 25 38 PM" src="https://user-images.githubusercontent.com/20427582/148834316-ce6563ee-bce0-4da0-81e3-c89640c6fb25.png">
<img width="520" alt="Screen Shot 2022-01-10 at 12 27 14 PM" src="https://user-images.githubusercontent.com/20427582/148834490-5ae8645b-82cd-4e52-a188-789fc4054bab.png">
<img width="635" alt="Screen Shot 2022-01-10 at 12 27 54 PM" src="https://user-images.githubusercontent.com/20427582/148834570-9402969c-58d6-4ede-91e6-4e2314be6eaf.png">
<img width="424" alt="Screen Shot 2022-01-10 at 12 28 29 PM" src="https://user-images.githubusercontent.com/20427582/148834711-894dc567-cfc0-4cfd-b8e7-eb96b87ba160.png">
<img width="649" alt="Screen Shot 2022-01-10 at 12 29 42 PM" src="https://user-images.githubusercontent.com/20427582/148834845-36f9ee0f-332a-4e44-8bcf-7ac2ba658078.png">
<img width="345" alt="Screen Shot 2022-01-10 at 12 31 00 PM" src="https://user-images.githubusercontent.com/20427582/148834937-753e0022-c71e-40c3-89de-ff00913256c3.png">
<img width="648" alt="Screen Shot 2022-01-10 at 12 32 28 PM" src="https://user-images.githubusercontent.com/20427582/148835130-ede11139-934c-408d-b2d7-6df864c3f7b8.png">
<img width="343" alt="Screen Shot 2022-01-10 at 12 34 10 PM" src="https://user-images.githubusercontent.com/20427582/148835395-ad406ffc-53bd-4573-9d91-396f5e5137d6.png">

### (Required) List of the scam account names

perfecthacksolution
miner606
doirhack01
marktech_26
autovmhack
cryptolordweb
hacsolution
irvinhack
sammyfunds02
tesohackservice
quipotech
belancash
marktech27
asphacoin
technopawnscom
primehacks01
earnflowcash
winfundshack
cylne1
hackerroberth
juohack01
bhadskyflly
bostontech
ronfunds
helpcare_solution
hacktivists1_

**Comment by PierceWHoward** [comment]
Question: How do you want us to report domains like this?
https://www.youtube.com/watch?v=JoU-5Mabsuc&lc=UgzHYJpb80IWArsg4-J4AaABAg
<img width="647" alt="Screen Shot 2022-01-10 at 12 38 47 PM" src="https://user-images.githubusercontent.com/20427582/148835908-7872651b-d994-4ec6-a1db-561272de0e2e.png">

**Comment by Kurdakov** [comment]
regarding question on spam domain, yes, submit as spam domain.
Regarding spam account, you seems missed documentation on what scam account means in submission:
quote:
"Spam Accounts: External social media accounts (instagram, telegram, etc) that are mentioned in scam comments as the point of contact for that particular scam. Usually these are scams advertising fake hacking services, free vbucks/robux, etc."
the reason - submitting youtube spam account names is almost useless due to the fact they frequently change name (or entire accounts)

**Comment by PierceWHoward** [comment]
> regarding question on spam domain, yes, submit as spam domain. Regarding spam account, you seems missed documentation on what scam account means in submission: quote: "Spam Accounts: External social media accounts (instagram, telegram, etc) that are mentioned in scam comments as the point of contact for that particular scam. Usually these are scams advertising fake hacking services, free vbucks/robux, etc." the reason - submitting youtube spam account names is almost useless due to the fact they frequently change name (or entire accounts)

Thanks for letting me know. Although, I'm confused about the second part because these are external social media accounts.

**Comment by Kurdakov** [comment]
"Although, I'm confused about the second part because these are external social media accounts."

yes, sorry, I probably meant to write in another place

**Comment by ThioJoe** [comment]
nice that's a lot of them. Also added that spam domain
