### ISSUE TITLE
Spam Domain Submission

### ISSUE THREAD

**Issue by s1072489** [ThioJoe/YT-Spam-Lists#73]
### Duplicate Domains

- [X] Yes, I checked that the domain **is not currently in the list**
- [X] I read <a href=https://github.com/ThioJoe/YT-Spam-Domains-List/wiki>the wiki</a> explaining each different categories and examples before submitting

### (Required) Spam Comment Direct Link

I have no idea how to get a direct link.
The following video only has 4 comments (including the spam comments):

https://www.youtube.com/watch?v=OZ9O921L2os

Please inform me as to how you can get a direct link

### (Optional) Screenshot of comments using the domain

![image](https://user-images.githubusercontent.com/79786672/149959661-c13c0e25-dcb9-45bf-9ede-01af89f34273.png)
![image](https://user-images.githubusercontent.com/79786672/149959737-7bc651e4-c721-472f-af98-95af57bdd9c6.png)

### (Required) List of the spam domains

- dhisex.uno
- casual.centre.baby

**Comment by ThioJoe** [comment]
Added

**Comment by PierceWHoward** [comment]
@s1072489 You can get a direct link by copying the link from the comment published time.
![Screenshot 2022-01-19 193653](https://user-images.githubusercontent.com/20427582/150268593-d9097192-ac5a-451e-a1ed-da36b06a3622.png)
