### ISSUE TITLE
Spam Domain Submission

### ISSUE THREAD

**Issue by PierceWHoward** [ThioJoe/YT-Spam-Lists#75]
### Duplicate Domains

- [X] Yes, I checked that the domain **is not currently in the list**
- [X] I read <a href=https://github.com/ThioJoe/YT-Spam-Domains-List/wiki>the wiki</a> explaining each different categories and examples before submitting

### (Required) Spam Comment Direct Link

https://www.youtube.com/watch?v=KYa6SDtJvJI&lc=Ugx-fTMXGh-Q7-NsGB54AaABAg
https://www.youtube.com/watch?v=KYa6SDtJvJI&lc=UgyZTn-Q0teEopV0d9Z4AaABAg
https://www.youtube.com/watch?v=KYa6SDtJvJI&lc=UgzUB5BN9BcAdiPNIeN4AaABAg
https://www.youtube.com/watch?v=yVlRpuiQJvY&lc=UgxvLQVGXFKMUHcVkBd4AaABAg
https://www.youtube.com/watch?v=UvFElDQnUcA&lc=UgzCea5_R3rgij_L7H54AaABAg
https://www.youtube.com/watch?v=UvFElDQnUcA&lc=Ugx3eveLAP1cPDN6-Kt4AaABAg

### (Optional) Screenshot of comments using the domain

<img width="582" alt="Screen Shot 2022-01-24 at 10 38 20 AM" src="https://user-images.githubusercontent.com/20427582/150843646-bb80b94e-a517-4213-afdb-3b08bba52706.png">
<img width="403" alt="Screen Shot 2022-01-24 at 10 38 43 AM" src="https://user-images.githubusercontent.com/20427582/150843713-526f6325-e374-4924-a8de-40ca86a68cc0.png">
<img width="431" alt="Screen Shot 2022-01-24 at 10 40 04 AM" src="https://user-images.githubusercontent.com/20427582/150844361-b4372526-573f-4dde-8d69-1a01b273ffcb.png">
<img width="662" alt="Screen Shot 2022-01-24 at 10 42 44 AM" src="https://user-images.githubusercontent.com/20427582/150844341-e9293714-571f-40bb-98c6-ca8caf50a5d1.png">
<img width="644" alt="Screen Shot 2022-01-24 at 10 44 55 AM" src="https://user-images.githubusercontent.com/20427582/150844748-8c5b469b-0ed1-4ac5-9c72-6802fa86a442.png">
<img width="636" alt="Screen Shot 2022-01-24 at 10 45 39 AM" src="https://user-images.githubusercontent.com/20427582/150844752-3bddd1c6-dec9-45cb-b75c-63c18a08eb98.png">

### (Required) List of the spam domains

netpayjob.com
cashend.me
dollarbrite.com
xbritclone.net
247hacks.net
orxhacks.com

**Comment by KendallDoesCoding** [comment]
These domains are in the scammers name and not in the comment huh? Smart scammers coz youtube usually deletes links in comments if creators have that option on.

**Comment by ThioJoe** [comment]
I was a bit slow on this one but just added it
