### ISSUE TITLE
Scam Thread Submission

### ISSUE THREAD

**Issue by KendallDoesCoding** [ThioJoe/YT-Spam-Lists#78]
### Duplicate Submissions

- [X] Yes, I checked that the name **is not currently in the list**
- [X] I read <a href=https://github.com/ThioJoe/YT-Spam-Domains-List/wiki>the wiki</a> explaining each different categories and examples before submitting

### (Required) Spam Comment Direct Link

https://www.youtube.com/watch?v=KKorSeSCTNc&lc=Ugz82kzHlntz3BES4b14AaABAg.9Xsz3XJdOb39XtDuYehU3K

### (Optional) Screenshot of comments referencing the scammer names

https://user-images.githubusercontent.com/58405537/152084713-3c6fea30-5e62-439e-8d9e-fff09272d2e1.png

### (Required) List of the scammer names

Mathew Scott
Randy O.
Berney Jack
Graham Foster
Lydia Anderson
Alexander Joe
Bamisaye Funmiloa
Micheal Scott

**Comment by KendallDoesCoding** [comment]
Taken from issue located here: https://github.com/ThioJoe/YT-Spammer-Purge/issues/468

**Comment by ThioJoe** [comment]
To reiterate, I only want to add the names the bots _mention_, not the usernames of the bots themselves. Though for the "mr lawrence tom" one, i have added that

**Comment by KendallDoesCoding** [comment]
> 

Oh yeah sorry, forgot about this.
