### ISSUE TITLE
Scam Thread Submission

### ISSUE THREAD

**Issue by prettybadatcoding** [ThioJoe/YT-Spam-Lists#82]
### Duplicate Submissions

- [X] Yes, I checked that the name **is not currently in the list**
- [X] I read <a href=https://github.com/ThioJoe/YT-Spam-Domains-List/wiki>the wiki</a> explaining each different categories and examples before submitting

### (Required) Spam Comment Direct Link

https://www.youtube.com/channel/UCfaJNgrumOdK3uQtw4gDxtA/community?lc=Ugz3hUZMYz0mD3c2Oq14AaABAg.9Y3Yix-PSMA9Y3ZKW_IbI6&lb=UgkxWhafcjHlbSK1aGewoKnXyXLejLbl201R

### (Optional) Screenshot of comments referencing the scammer names

<img width="513" alt="image" src="https://user-images.githubusercontent.com/97399364/152652585-ffbc167a-b37d-48ba-9d8d-2e32c5586923.png">

### (Required) List of the scammer names

mr steve miley

**Comment by ThioJoe** [comment]
added
