### ISSUE TITLE
Spam Domain Submission

### ISSUE THREAD

**Issue by prettybadatcoding** [ThioJoe/YT-Spam-Lists#83]
### Duplicate Domains

- [X] Yes, I checked that the domain **is not currently in the list**
- [X] I read <a href=https://github.com/ThioJoe/YT-Spam-Domains-List/wiki>the wiki</a> explaining each different categories and examples before submitting

### (Required) Spam Comment Direct Link

https://www.youtube.com/watch?v=C_eYLWLsWPg&lc=UgxrUl_j7yI2nnY1Pv54AaABAg.9Y4TzVnsG9f9Y4U1BPW9XJ

### (Optional) Screenshot of comments using the domain

<img width="478" alt="image" src="https://user-images.githubusercontent.com/97399364/152664315-de040abf-9bfd-4365-a304-c4cd4c8061b9.png">

### (Required) List of the spam domains

specialdate.my.id/alexandra?

**Comment by ThioJoe** [comment]
added
