### ISSUE TITLE
Spam Domain Submission

### ISSUE THREAD

**Issue by prettybadatcoding** [ThioJoe/YT-Spam-Lists#84]
### Duplicate Domains

- [X] Yes, I checked that the domain **is not currently in the list**
- [X] I read <a href=https://github.com/ThioJoe/YT-Spam-Domains-List/wiki>the wiki</a> explaining each different categories and examples before submitting

### (Required) Spam Comment Direct Link

https://www.youtube.com/watch?v=DdZBfuJYqpc&lc=UgyNULuTkvwhuEj2Qx14AaABAg
(I noticed that these scam videos have a lot of spam comments)

### (Optional) Screenshot of comments using the domain

<img width="460" alt="image" src="https://user-images.githubusercontent.com/97399364/152693237-a6ad24d8-86ca-4847-9281-9f63048b5e7c.png">

### (Required) List of the spam domains

rr.fafa.bar

**Comment by ThioJoe** [comment]
added
