### ISSUE TITLE
Spam Domain Submission

### ISSUE THREAD

**Issue by tpguy825** [ThioJoe/YT-Spam-Lists#86]
### Duplicate Domains

- [X] Yes, I checked that the domain **is not currently in the list**
- [X] I read <a href=https://github.com/ThioJoe/YT-Spam-Domains-List/wiki>the wiki</a> explaining each different categories and examples before submitting

### (Required) Spam Comment Direct Link

https://www.youtube.com/watch?v=w9IVL1J1QaY&lc=UgxHGLivbQFuqFyILb94AaABAg.9YBBwVSu96r9YBCDpQc7I1
https://www.youtube.com/watch?v=0VtY2UyHeD4&lc=UgwtWgBj6abcaY3pMa54AaABAg.9YT7TKn6_4t9YT9YlLZo6p

### (Optional) Screenshot of comments using the domain

![image](https://user-images.githubusercontent.com/75158953/154066621-5bdadbcb-9d8b-470d-a52f-e156e1a1e2c4.png)
![image](https://user-images.githubusercontent.com/75158953/154066405-e5fb829a-b073-47df-b55a-1d00f5fc9512.png)

### (Required) List of the spam domains

snapgirls.uno
bigasschubby.com

**Comment by ThioJoe** [comment]
Added
