### ISSUE TITLE
Spam Domain Submission

### ISSUE THREAD

**Issue by tpguy825** [ThioJoe/YT-Spam-Lists#88]
### Duplicate Domains

- [X] Yes, I checked that the domain **is not currently in the list**
- [X] I read <a href=https://github.com/ThioJoe/YT-Spam-Domains-List/wiki>the wiki</a> explaining each different categories and examples before submitting

### (Required) Spam Comment Direct Link

https://www.youtube.com/watch?v=oYarsGngBMA&lc=Ugxa6C7BnuvJDgHbJ-d4AaABAg.9Y3wANxnn969Y3wLU_xnYN
https://www.youtube.com/watch?v=oYarsGngBMA&lc=UgwRBYiqFmySmLs4MmF4AaABAg.9Y3wXAn64mr9Y5Jlq94kn6

### (Optional) Screenshot of comments using the domain

![image](https://user-images.githubusercontent.com/75158953/154330181-0a96f3c9-8244-4533-8602-5bd78afe1321.png)
![image](https://user-images.githubusercontent.com/75158953/154330959-a7bb08c3-419c-40bd-8ad5-baa126b9ec01.png)

### (Required) List of the spam domains

youngunt.online
snapgirls.date

**Comment by ThioJoe** [comment]
Added
