### ISSUE TITLE
Four spam accounts

### ISSUE THREAD

**Issue by prettybadatcoding** [ThioJoe/YT-Spam-Lists#89]
### Duplicate Submissions

- [X] Yes, I checked that the account name **is not currently in the list**
- [X] I read <a href=https://github.com/ThioJoe/YT-Spam-Domains-List/wiki>the wiki</a> explaining each different categories and examples before submitting

### (Required) Spam Comment Direct Link

https://www.youtube.com/watch?v=1zLsUhOCqyU&lc=Ugyz2uaENlXxw45sNkV4AaABAg
https://www.youtube.com/watch?v=1zLsUhOCqyU&lc=UgyxYB-uYs856mn6URl4AaABAg
https://www.youtube.com/watch?v=1zLsUhOCqyU&lc=UgzUXdvclGp_xRJ6osB4AaABAg
https://www.youtube.com/watch?v=1zLsUhOCqyU&lc=UgwdpOTiGvbpXwlu93B4AaABAg

### (Optional) Screenshot of comments referencing the scam account

<img width="424" alt="image" src="https://user-images.githubusercontent.com/97399364/154991487-5b1d991b-3e1d-4b87-9e35-76b48650abac.png">

<img width="445" alt="image" src="https://user-images.githubusercontent.com/97399364/154991612-5cd912de-40aa-4beb-9d70-72a1baea4df1.png">

<img width="304" alt="image" src="https://user-images.githubusercontent.com/97399364/154991851-d4ea9e27-d678-4551-95de-10fe224286c6.png">

<img width="456" alt="image" src="https://user-images.githubusercontent.com/97399364/154992446-095a57d2-e2af-48be-8008-32cb868c8667.png">

### (Required) List of the scam account names

flashpunchtech
veratti100
z5cracks
rejoicehack

**Comment by prettybadatcoding** [comment]
Irrelevant: Do you think the people behind these bots know that this program exist?

**Comment by Firecul** [comment]
> Irrelevant: Do you think the people behind these bots know that this program exists?

Some of them probably do, I'd imagine a few have been changing their names to try and avoid the filters or switching up what they copy and paste.

**Comment by ThioJoe** [comment]
added
