### ISSUE TITLE
One scam domain, served fresh just for you!

### ISSUE THREAD

**Issue by prettybadatcoding** [ThioJoe/YT-Spam-Lists#90]
### Duplicate Domains

- [X] Yes, I checked that the domain **is not currently in the list**
- [X] I read <a href=https://github.com/ThioJoe/YT-Spam-Domains-List/wiki>the wiki</a> explaining each different categories and examples before submitting

### (Required) Spam Comment Direct Link

https://www.youtube.com/watch?v=1zLsUhOCqyU&lc=UgyjoOc5mKTz50uzi1N4AaABAg

### (Optional) Screenshot of comments using the domain

<img width="417" alt="image" src="https://user-images.githubusercontent.com/97399364/154993485-ddef5a48-6628-4e9f-a779-4eb7540af04c.png">

### (Required) List of the spam domains

blackairhack.com

**Comment by ThioJoe** [comment]
added
