### ISSUE TITLE
Some more scam threads

### ISSUE THREAD

**Issue by prettybadatcoding** [ThioJoe/YT-Spam-Lists#91]
### Duplicate Submissions

- [X] Yes, I checked that the name **is not currently in the list**
- [X] I read <a href=https://github.com/ThioJoe/YT-Spam-Domains-List/wiki>the wiki</a> explaining each different categories and examples before submitting

### (Required) Spam Comment Direct Link

https://www.youtube.com/watch?v=1zLsUhOCqyU&lc=UgwdwywKsWinuDaYHlJ4AaABAg.9YRhWqoqkEX9YRhnpKjV8H

https://www.youtube.com/watch?v=1zLsUhOCqyU&lc=Ugxmp4-oR4ADdkYvG-F4AaABAg
https://www.youtube.com/watch?v=1zLsUhOCqyU&lc=Ugz_gZbWb7uo7IynSVp4AaABAg.9YW95PuupHO9YW9RO40I7a

https://www.youtube.com/watch?v=1zLsUhOCqyU&lc=UgwdirjL44zsy6M8qkl4AaABAg.9YURQxlae6G9YURXd9St0M

### (Optional) Screenshot of comments referencing the scammer names

<img width="380" alt="image" src="https://user-images.githubusercontent.com/97399364/154994572-3cd4970b-7700-43f2-ab57-9c22a0e37996.png">

<img width="433" alt="image" src="https://user-images.githubusercontent.com/97399364/154994855-52bb2cf4-f161-4fbe-9fbf-a6edf26f9484.png">

<img width="361" alt="image" src="https://user-images.githubusercontent.com/97399364/154995221-f92669a8-576b-42d1-a7c1-4bd5bb1a45f5.png">

<img width="386" alt="image" src="https://user-images.githubusercontent.com/97399364/154995410-9f813ad3-fc56-400e-81a3-9986b7ea838e.png">

### (Required) List of the scammer names

mrs charlotte junko walsh
expert trader richard carson
expert mrs diane walter
bettina s. bergin

**Comment by ThioJoe** [comment]
added
