### ISSUE TITLE
Scam Account Submission

### ISSUE THREAD

**Issue by Sarah1390** [ThioJoe/YT-Spam-Lists#96]
### Duplicate Submissions

- [X] Yes, I checked that the account name **is not currently in the list**
- [X] I read <a href=https://github.com/ThioJoe/YT-Spam-Domains-List/wiki>the wiki</a> explaining each different categories and examples before submitting

### (Required) Spam Comment Direct Link

ttps://www.youtube.com/watch?v=GOJ3Rm9DlXE&lc=UgxBopfBckMv-jftkfN4AaABAg

### (Optional) Screenshot of comments referencing the scam account

![Screenshot 2022-03-19 114611](https://user-images.githubusercontent.com/97075311/159128251-8413a051-2e07-4cfc-87e2-4dadc3d629fd.png)

### (Required) List of the scam account names

f r e e r o b u x on my profile

**Comment by Firecul** [comment]
I think [your other issue](https://github.com/ThioJoe/YT-Spammer-Purge/issues/749) is a more appropriate place for this

**Comment by ThioJoe** [comment]
Yea the other post is fine
